
name: CI
on:
  push:
    branches: [ "main", "develop", "release" ]

  pull_request:
    branches: [ "main", "develop", "release" ]

jobs:
  test_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: just run test script
        run: bash -n testfile.sh

  run_script:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} #This prevent the second stage to trigger on PR
    needs: test_script
    steps:
      - uses: actions/checkout@v3
      - name: Run shell script
        run: bash testfile.sh $GITHUB_ACTOR
